CREATE DATABASE IF NOT EXISTS notes_app;

USE notes_app;

CREATE TABLE IF NOT EXISTS notes (
  id CHAR(36) PRIMARY KEY,
  text TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  pinned TINYINT(1) NOT NULL DEFAULT 0,
  ai_summary TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
